DROP SEQUENCE G_GenreID; 
DROP SEQUENCE M_MovieID; 
DROP SEQUENCE P_PersonID; 
DROP SEQUENCE MC_MovCharID; 

DELETE FROM MovieGenre;
DELETE FROM MovieCharacter;
DELETE FROM Person;
DELETE FROM Genre;
DELETE FROM Movie;

DROP TABLE MovieGenre;
DROP TABLE MovieCharacter;
DROP TABLE Person;
DROP TABLE Genre;
DROP TABLE Movie;